apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ntam5d4gr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ntam5d4gr-nodejs 
  name: ntam5d4gr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ntam5d4gr-nodejs 
